# Generated by Django 3.2.6 on 2021-08-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_auto_20210826_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='duracao_emprestimo',
            field=models.DurationField(blank=True, null=True),
        ),
    ]