# Generated by Django 4.2.11 on 2024-04-28 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0035_livros_localizacao_retirada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 19, 1, 10, 40430)),
        ),
    ]
