# Generated by Django 4.2.11 on 2024-04-28 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0036_alter_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='localizacao_retirada',
        ),
        migrations.AddField(
            model_name='emprestimos',
            name='localizacao_retirada',
            field=models.CharField(default=1, max_length=100, verbose_name='Localização Retirada'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 19, 3, 11, 498832)),
        ),
    ]
