# Generated by Django 4.2.11 on 2024-04-28 22:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0037_remove_livros_localizacao_retirada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 19, 57, 29, 530913)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='exemplares_disponiveis',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
