# Generated by Django 4.2.11 on 2024-05-05 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0038_alter_emprestimos_data_emprestimo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 5, 17, 40, 33, 721093)),
        ),
    ]
