# Generated by Django 4.2.11 on 2024-05-10 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0040_livros_observacoes_gerais_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 10, 9, 35, 24, 571232)),
        ),
    ]
