# Generated by Django 4.2.13 on 2024-05-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0045_rename_duracao_emprestimo_emprestimos_tempo_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='localizacao_retirada',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização Retirada'),
        ),
    ]
