# Generated by Django 5.1.7 on 2025-03-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0049_evento_emprestimos_duracao_emprestimo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='duracao_emprestimo',
        ),
    ]
