# Generated by Django 5.1.7 on 2025-03-22 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0050_remove_emprestimos_duracao_emprestimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='genero',
            field=models.CharField(blank=True, max_length=50, verbose_name='Gênero'),
        ),
    ]
